#!/usr/bin/env zsh
set -euo pipefail

# Ensure we run from the project root
SCRIPT_DIR=${0:a:h}
PROJECT_ROOT=${SCRIPT_DIR:h}
cd "$PROJECT_ROOT"

LOCK_FILE="Sweetpad.lock"
FILES=("sweetpad.json")

usage() {
  cat <<USAGE
Usage: scripts/sweetpad_guard.sh [--update]

Validates that critical Sweetpad files exist.
Automatically updates $LOCK_FILE if changes are detected to ensure connection stays intact.
USAGE
}

if [[ ${1:-} == "-h" || ${1:-} == "--help" ]]; then
  usage
  exit 0
fi

# Function to update lock file
update_lock() {
  echo "Updating Sweetpad lock file..."
  {
    echo "# Auto-generated by scripts/sweetpad_guard.sh"
    for file in "${FILES[@]}"; do
      if [[ ! -f "$file" ]]; then
        echo "error: $file not found" >&2
        exit 1
      fi
      hash=$(shasum -a 256 "$file" | awk '{print $1}')
      echo "$file=$hash"
    done
  } > "$LOCK_FILE"
  echo "Sweetpad lock updated."
}

if [[ ${1:-} == "--update" ]]; then
  update_lock
  exit 0
fi

if [[ ! -f "$LOCK_FILE" ]]; then
  echo "Notice: $LOCK_FILE missing. Creating it..."
  update_lock
fi

guard_status=0
needs_update=0

for file in "${FILES[@]}"; do
  if [[ ! -f "$file" ]]; then
    echo "❌ $file missing" >&2
    guard_status=1
    continue
  fi
  
  # Get current file hash
  current_hash=$(shasum -a 256 "$file" | awk '{print $1}')
  
  # Get expected hash from lock file
  expected_hash=$(grep "^$file=" "$LOCK_FILE" 2>/dev/null | cut -d'=' -f2 || true)
  
  if [[ -z "$expected_hash" ]]; then
    echo "Notice: $file not found in lock file. Will update."
    needs_update=1
  elif [[ "$expected_hash" != "$current_hash" ]]; then
    echo "Notice: $file changed. Updating lock file to maintain connection."
    needs_update=1
  else
    echo "✅ $file verified"
  fi

done

if [[ $needs_update -eq 1 && $guard_status -eq 0 ]]; then
  update_lock
fi

if [[ $guard_status -ne 0 ]]; then
  echo "Sweetpad guard check failed. Files are missing." >&2
fi

exit $guard_status
